# Generated by Django 5.2.8 on 2025-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dictionaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedword',
            name='hindi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedword',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
